### ISSUE TITLE
SignShop not recognizing CraftConomy currency.

### ISSUE THREAD

**Issue by rafe2486** [wargamer/SignShop#101]
When I try to buy from a sign, it gives the message:
Could not pass event SSMoneyTransactionEvent to SignShop v3.5.0

And when I set prices it does not show a price in the chat.
![2020-10-25_01 14 52](https://user-images.githubusercontent.com/67610532/97099452-9ad0a000-165f-11eb-9826-3413c4bc366a.png)

Plugins on this server are:
Vault
GriefPrevention
CraftConomy3*
SignShop
SetHome
SilkSpawners
SinglePlayerSleep
PlayerHeads
DeadChest
EntityTrackerFixer

**Comment by weaves7** [comment]
Please give me a paste of your startup log and the full error.

**Comment by rafe2486** [comment]
26.10 02:10:07 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.has(Economy_Craftconomy3.java:284) ~[?:?]
26.10 02:10:07 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.has(Economy_Craftconomy3.java:136) ~[?:?]
26.10 02:10:07 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.has(AbstractEconomy.java:33) ~[?:?]
26.10 02:10:07 [Server] INFO at org.wargamer2010.signshop.player.SignShopPlayer.hasNoMoney(SignShopPlayer.java:230) ~[?:?]
26.10 02:10:07 [Server] INFO at org.wargamer2010.signshop.listeners.sslisteners.DefaultMoneyTransaction.onSSMoneyTransaction(DefaultMoneyTransaction.java:43) ~[?:?]
26.10 02:10:07 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.wargamer2010.signshop.SignShop.scheduleEvent(SignShop.java:88) ~[?:?]
26.10 02:10:07 [Server] INFO at org.wargamer2010.signshop.operations.takePlayerMoney.checkRequirements(takePlayerMoney.java:21) ~[?:?]
26.10 02:10:07 [Server] INFO at org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:265) ~[?:?]
26.10 02:10:07 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:154) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1385) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:07 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Multicraft] Skipped 8 lines due to rate limit (30/s)
26.10 02:10:08 [Server] ERROR Could not pass event SSMoneyTransactionEvent to SignShop v3.5.0
26.10 02:10:08 [Server] INFO java.lang.NullPointerException: null
26.10 02:10:08 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.has(Economy_Craftconomy3.java:284) ~[?:?]
26.10 02:10:08 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.has(Economy_Craftconomy3.java:136) ~[?:?]
26.10 02:10:08 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.has(AbstractEconomy.java:33) ~[?:?]
26.10 02:10:08 [Server] INFO at org.wargamer2010.signshop.player.SignShopPlayer.hasNoMoney(SignShopPlayer.java:230) ~[?:?]
26.10 02:10:08 [Server] INFO at org.wargamer2010.signshop.listeners.sslisteners.DefaultMoneyTransaction.onSSMoneyTransaction(DefaultMoneyTransaction.java:43) ~[?:?]
26.10 02:10:08 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.wargamer2010.signshop.SignShop.scheduleEvent(SignShop.java:88) ~[?:?]
26.10 02:10:08 [Server] INFO at org.wargamer2010.signshop.operations.takePlayerMoney.checkRequirements(takePlayerMoney.java:21) ~[?:?]
26.10 02:10:08 [Server] INFO at org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:265) ~[?:?]
26.10 02:10:08 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:08 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-191]
26.10 02:10:11 [Multicraft] Skipped 7 lines due to rate limit (30/s)

**Comment by weaves7** [comment]
The console has skipped some lines so this is not the full startup and error. Please copy and paste what is in your latest.log to a site such as pastebin, save; then paste the link here.

**Comment by weaves7** [comment]
I did try a few things that worked for me. 
- Make sure Craftconomy3 is setup by doing /ccsetup then following the instructions
- Make sure you have the latest Spigot/Paper build version
- Try Phoenix616's [fork of Craftconomy3](https://github.com/Phoenix616/craftconomy3/) you can download it [here](https://ci.minebench.de/job/craftconomy3/).

**Comment by weaves7** [comment]
Assuming this has been resolved. Re-open with more information if it is not.
