### ISSUE TITLE
Bug SignShop PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by Spinogl** [wargamer/SignShop#102]
Hello,
I allow myself to contact you in order not to put a bad note to the SignShop plugin, but I have an error when launching the plugin (under PaperSpigot 1.8.8) which bothers me a lot (I hate errors).
So I would have liked to know if it would be possible to correct this error?

https://hastebin.com/kawaxojiwo.less or http://pastebin.fr/70676

Sincerely,
Spinogl

**Comment by weaves7** [comment]
I do not officially support Minecraft versions prior to 1.13 since that is before I took over the project. However I will try to help you if I can. Please provide a hastebin of your entire latest.log along with the full error.
