### ISSUE TITLE
** on top of signs despite having correct permissions

### ISSUE THREAD

**Issue by xdav1dofficial** [wargamer/SignShop#106]
Hello, 

The players on my server have tried putting buy signs down in a region that they own in worldguard. Allow-shop is set to allow and they have the bypass permissions anyway. I cant seem to work out why the sign for them keeps going to ** at the top when they type [buy]

Can anyone help?

**Comment by weaves7** [comment]
Signshop does not have anything in it that does this. You have another plugin interfering, look for other plugins that have to do with signs and try removing them one at a time until you find the one that is causing the problem.
