### ISSUE TITLE
Barrels incorrectly show shop out of stock when items are available

### ISSUE THREAD

**Issue by oranges13** [wargamer/SignShop#107]
We have had a recurring issue with sign shops using barrels showing out of stock when used even though there is stock in the container.

For example, a player was trying to sell fireworks, but the sign is red and also reports that the shop is out of stock when you right-click on it.

![2021-02-21_16 44 28](https://user-images.githubusercontent.com/755110/108639834-97f68800-7464-11eb-8a46-b3e1b3aff2a7.png)
![2021-02-21_16 44 41](https://user-images.githubusercontent.com/755110/108639839-9cbb3c00-7464-11eb-9e92-b10c98ec4996.png)

This may be related to #83 since they are using named items, but we've had recurring issues with barrels + sign shops, usually remaking them with chests fixes the problem but we'd like our players to be able to use any container to make shops.

**Comment by weaves7** [comment]
I cannot seem to reproduce this issue. I made a custom named firework with a couple of effects and even some lore and setup a shop to sell 1 from a barrel. After filling the shop with a stack I was able to buy one at a time until the shop was actually empty. I used Spigot 1.16.5 for this test with minimal plugins. I also did a restart to make sure it still worked after a restart. Perhaps you have a different setup? Please reply with your full setup as well as any steps that I can use to reproduce the issue consistently.

**Comment by oranges13** [comment]
We are using paper 1.16.4 and quite a few other plugins. Essentials, Luckperms, shopkeepers, multiverse, world edit, world guard. Others but I don't know if they interact with signs or containers.

Do you think it would make any difference if this shop was created in the Nether versus the overworld?

**Comment by weaves7** [comment]
You should test with minimal plugins. The nether should not matter. I will test with paper after work.
