### ISSUE TITLE
Request: Confirming a sale if the cost is more than X

### ISSUE THREAD

**Issue by TomLewis** [wargamer/SignShop#110]
We have an issue with people tricking other players to click signs to drain their balance, if you can add a check for if the price they are paying on the sign is more than X in the config, this would require a conformation to pop up to confirm the sale.

I suggest popping up a book with a [buy] and [cancel] this way it's extremely obvious and in their face, we can also include in the book exactly what they are buying and for how much.

**Comment by weaves7** [comment]
This is along the lines of #109 and will be tracked there.
