### ISSUE TITLE
Request: Add Separate Permission to Break Other Users Shops

### ISSUE THREAD

**Issue by vapecloudbear** [wargamer/SignShop#112]
Currently, Signshop.SuperAdmin is the only perm that allows deletion of other players shops. I would love to see a separate perm for shop deletion. I would like server admins to be able to remove shops without have permission to create infinite buy/sell signs. This would help greatly with the administration of player’s shops without risking player economy from a rouge staff member.

**Comment by weaves7** [comment]
Here is a dev build for anyone following along https://github.com/weaves7/SignShop/releases/tag/v3.5.2-dev
