### ISSUE TITLE
The sign shop

### ISSUE THREAD

**Issue by AllStarDinner** [wargamer/SignShop#113]
So whenever i try and make a shop, I stock it up fully. Here is an example, every slot has 1 diamond. But when i make the sign is says i am selling 27 diamonds for $50 (this was just a test to see how it worked) How can i make it to where when a player buys they only buy 1 diamond

**Comment by weaves7** [comment]
Only have 1 diamond in the chest while linking to the sign. Then fill it up. Whatever is in the chest during the linking process will be what is sold, regardless of what the sign says.
