### ISSUE TITLE
Signs change to ** instead of remaining as Buy

### ISSUE THREAD

**Issue by DietKola** [wargamer/SignShop#115]
I've been trying to allow non-admins to make signs. I have the permissions     
    - Signshop.Signs.*
    - Signshop.BypassShopPlots.*
    - Signshop.IgnoreMax
    - Signshop.ChangeOwner
    - Signshop.CopyPaste
    - Signshop.SuperAdmin
    - Signshop.Admin.*
    
given to ALL users and they still don't work. I disabled -color in essentials, spawn protection is 0, etc. and they still don't work. Can anyone help or explain why the signs change to **

I can provide anything else if needed. Thanks :)

**Comment by weaves7** [comment]
I assume that you figured out the solution.

 For anyone else that stumbles across this, the problem is not caused by signshop. Signshop does not put ``**`` on signs so they must have had another plugin interfering. Look for other plugins that use or edit signs.
