### ISSUE TITLE
Bug for 1.17.1

### ISSUE THREAD

**Issue by BboyZeroOne** [wargamer/SignShop#118]
Not sure what's wrong but it does not work on 1.17.1

https://pastebin.com/4CCw6pzV

**Comment by weaves7** [comment]
It does work with 1.17.1. Please paste your entire startup log.

**Comment by BboyZeroOne** [comment]
Here

https://pastebin.com/qyZpTyZB

**Comment by weaves7** [comment]
Try this dev build https://github.com/weaves7/SignShop/releases/tag/v3.5.2-dev
