### ISSUE TITLE
SignShop sometimes not working correctly (signs)

### ISSUE THREAD

**Issue by sakulmore** [wargamer/SignShop#122]
Hello, i have a problem with signs in SignShop plugin.

Sometimes happening me that players (with me) can't buy items from signs. The sign is as "classic" sign and not as SignShop sign.

Example video here: https://youtu.be/ZwB4FK6rZe8

If i break the sign, and create it again, then works again correctly.

**Comment by weaves7** [comment]
Does the sign work again if you are op? Pastebin your startup log.

**Comment by sakulmore** [comment]
> Does the sign work again if you are op? Pastebin your startup log.

It doesn't matter if i'm OP or DEOP (classic player). Not working in both situations.

https://pastebin.com/H2HRQimJ

**Comment by weaves7** [comment]
What do you mean by "classic" sign? Try without ColoredSigns installed. Make sure you do /restart not /reload.

**Comment by sakulmore** [comment]
Hi, sorry for late answer. Today again nobody can't buy item. Here is video: https://youtu.be/j0AfPiVMq4Q

If i recreate the sign, works again correctly.

**Comment by sakulmore** [comment]
Okay, now i finded the problem.

If player break that sign, can't bough that item (see video above).

**Comment by weaves7** [comment]
Since you are not getting a message from signshop, I think another plugin is canceling the click before signshop sees it. Did you try disabling ColoredSigns and any other plugin that works with signs. If you use Essentials make sure you disable all of the Essentials signs by commenting them out in the Essentials config.

**Comment by sakulmore** [comment]
Okay, i will try disabling ColoredSigns. I'm using CMI instead of Essentials.

**Comment by sakulmore** [comment]
Alright, i thing it's causing by coloredsigns plugin. I disabled it, changed in CMI config one row, and looks works good now.

**Comment by weaves7** [comment]
Awesome, I will close this for now. If you have more problems feel free to open a new ticket or join the Discord.
