### ISSUE TITLE
Issue with iSell signs when sneaking

### ISSUE THREAD

**Issue by TerdyTheTerd** [wargamer/SignShop#125]
A fun little issue, when sneak clicking an iSell sign it will take two of the items but only pay you for one of them, very useful!

**Comment by weaves7** [comment]
Please pastebin your startup log and link it here.

**Comment by TerdyTheTerd** [comment]
Apologies, it appears that this was an isolated incident, after recreating the sign and removing the linked inventory the signs function as expected. Not sure what was causing the initial issue but I can't recreate it now :/
