### ISSUE TITLE
Skipping Ranks [Promote}

### ISSUE THREAD

**Issue by RoachBoi** [wargamer/SignShop#126]
Hello all,
So I'm making a ranking system in my server and signshop basically supports the whole economy in the server with selling and trading and I love it. Ive been testing out the [Promote] feature and I really like it. However it allows people to skip over ranks entirely and I do not want this.  For example if someone is the default rank, and  the next rank is citizen, and the rank after that is farmer. They can completely skip citizen and go straight to farmer.  Is there a way for the promote feature to require the previous rank to be promoted?
Thanks!

**Comment by weaves7** [comment]
It does not have that built into it but you can link a [restricted] sign to each [promote] sign with the previous rank listed on the [restricted] sign.

**Comment by RoachBoi** [comment]
> It does not have that built into it but you can link a [restricted] sign to each [promote] sign with the previous rank listed on the [restricted] sign.

Thank you!  Im currently trying to link the restricted sign to the promote signs and I cant seem to get them to link. Im punching both signs with redstone and they dont link. How do you link them?

**Comment by weaves7** [comment]
IIRC you just make the restricted sign then punch it with redstone then the sign you want to restrict. What messages do you get?

**Comment by RoachBoi** [comment]
Yes I did exactly that. It gives me the message 'this sign can only be destroyed with a golden axe'.  I tested trying to link the restricted sign to a regular shop as well and I get the same message.  When I right click the restricted sign it say it is not linked to any signs.

**Comment by weaves7** [comment]
Pastebin your startup log.

**Comment by RoachBoi** [comment]
https://pastebin.com/7X4h4nTj

**Comment by weaves7** [comment]
I doubt it is the problem but you should go ahead and update SignShop to v3.6.1. Otherwise hold on while I test.

**Comment by RoachBoi** [comment]
Okay I updated signhop. The problem still persists. Do you think its because my essentials plugin isnt up to date or is that unrelated?

**Comment by weaves7** [comment]
I just tested linking a restricted sign to a promote sign and it works for me. Essentials should not have any effect on this unless Signshop mentions anything about it during startup. Have you tried removing both signs and starting over? What other messages did you get while creating the restricted and promote signs?

**Comment by RoachBoi** [comment]
Yes I tried starting over with both signs. I made the promote sign and activated it, then made the restricted sign, punched it with redstone then punched the promote sign and thats when it would say you cant destroy this sign. I also tried creating both signs without activating either then activated the restricted then the promote. Still says there are no signs linked to the restricted sign. Using redstone with left click on all the actions.

**Comment by weaves7** [comment]
Just in case it is interfering, do you have all of the Essentials signs disabled? Can I join your server?

**Comment by RoachBoi** [comment]
Yes you can, I wont be on for a few hours though. Its terradax.apexmc.co . I do not have the essentials signs disabled.

**Comment by weaves7** [comment]
Ok, I am on your server.  I will afk and play something else until you get on. If I am not there it is because I went to bed. You may have to punch me or something to get my attention. Nice looking spawn btw.

**Comment by weaves7** [comment]
You can also join the discord for easier communication.
