### ISSUE TITLE
Permissions are not working at all (Tried Verbose too)

### ISSUE THREAD

**Issue by TomLewis** [wargamer/SignShop#127]
LuckPerms v5.3.86
PurPur 1.17.1
SignShop 3.6.1

I have used Signshop for over 6+ years, Im just upgrading from 1.12 to 1.17, from /lp verbose it looks like the permissions haven't changed when creating signs, I can create signs when im OP, but as a rank that inherits * permissions, it still does not work, Permission denied all the time, Ive even tried signshop.* to see if theres a missing permission, still permission denied.

I am not using permits.

`"You don't have permission to create this sign!`

**Comment by weaves7** [comment]
Do you have LP configured to recognize * perms? What perms show up in lp verbose? Are you using a filter on your lp verbose that could be limiting what perms checks you see? Very little has changed as far as perms go in SignShop. Pastebin you startup log.

**Comment by TomLewis** [comment]
> Do you have LP configured to recognize * perms?
Yes, wildcards are active.

> What perms show up in lp verbose?
The ones that have always been there, that are in the docs, for example, I was testing with `signshop.signs.donate` and this was the verbose:
![Screenshot 2021-12-23 21 42 17](https://user-images.githubusercontent.com/144046/147351550-ff61949c-1b4d-45e4-b50f-b57d03ef1210.png)

>Are you using a filter on your lp verbose that could be limiting what perms checks you see?
Only filtering to the person I'm testing on, so its showing all perms for that user, not all users online.

>Very little has changed as far as perms go in SignShop
I know, which is why this is worrying, I have been using SignShop for close to 9 years, I'm moving from 1.12.2 to 1.17.1/1.18, so all my permissions have been working for years previously in 1.12.2, which is why its very odd that this would just break like this.

**Comment by weaves7** [comment]
Did you change permissions managers? It almost looks like LP is not applying perms correctly, not that I think LP is broken but perhaps there was something lost in the upgrade or, and don't take this the wrong way, but are you sure you are editing the correct player, group, or even server? Are you sure the player inherits the correct group? I only ask these things since I have had someone do them before, I have learned to make no assumptions. Signshop is making the correct permissions checks but for some reason LP has them undefined. Also please note that ```signshop.*``` would also give denylink perms. You would need to use ```Signshop.Signs.*``` to give access to all non op signs. Worldguard should not interfere in this case since you don't have it enabled. Also there should be a Worldguard bypass permission check if it was active. I would still like to see your startup log. If you do not want to share it here you could PM me on Spigot or Discord. Replies are usually quicker on Discord. https://discord.gg/4wnyysf

**Comment by TomLewis** [comment]
Nope, been using LuckPerms years and years.
Yup all my groups/perms were brought over from 1.12.2 and previously worked perfectly fine, I've not had to touch any perms really for many plugins, only update permissions for my new chat plugin, everything else is working apart from SignShop which no permissions seem to work at all.

I did also try with `Signshop.Signs.*` 

The startup log is fine, there is no conflicts or errors with signshop, but with verbose it looks like its checking for the permissions.

SignShop has always been on of the longest plugins to load when the server stars due to just how many sellers I have.


```
[16:33:22] [Server thread/INFO]: [SignShop] Loading SignShop v3.6.1
[16:34:03] [Server thread/INFO]: [SignShop] Enabling SignShop v3.6.1
[16:34:05] [Server thread/INFO]: [SignShop] Checking data version.
[16:34:05] [Server thread/INFO]: [SignShop] Your data is current.
[16:34:22] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7621, 28, 1433) exceeds the maximum amount of chests per shop!
[16:34:29] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7610, 48, 1419) exceeds the maximum amount of chests per shop!
[16:34:29] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7621, 28, 1435) exceeds the maximum amount of chests per shop!
[16:34:31] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7621, 28, 1434) exceeds the maximum amount of chests per shop!
[16:34:33] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7621, 28, 1436) exceeds the maximum amount of chests per shop!
[16:34:34] [Server thread/WARN]: [SignShop] Shop in world 'PirateCraft_1' at (7621, 28, 1437) exceeds the maximum amount of chests per shop!
[16:34:35] [Server thread/INFO]: [SignShop] Using worth information from Essentials.
[16:34:35] [Server thread/INFO]: [SignShop] Thank you for enabling metrics!
[16:34:35] [Server thread/INFO]: [SignShop] v3.6.1 Enabled
```
Thats all SignShop logs at boot.

**Comment by weaves7** [comment]
Try this dev build https://github.com/weaves7/SignShop/releases/tag/v3.6.1.3-dev

**Comment by TomLewis** [comment]
Aha brilliant, this seems to have worked with the donate sign.
Im not about to do much more testing today, but hopefully some of my staff can test while im away to check the other signs!
Thank you.
