### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RAPHAEL599** [wargamer/SignShop#144]
How I can change the sign color?
![2022-04-16_19 56 51](https://user-images.githubusercontent.com/73084300/163693748-56394edd-12d1-43ab-96bc-82d2bdeb6c91.png)

**Comment by weaves7** [comment]
The color of the first line, in this case [iBuy] is determined by stock status and is not able to be changed. Black is an incompletely setup sign, blue is a functional and in stock sign and red is an out of stock sign. The other lines can have colors but SignShop does not handle them. You would need another plugin that handles coloring signs. There are a few out there but I have not tested any enough to make any recommendations. I will caution you that some plugins that color signs may interfere with SignShop, for example Essentials is compatible with SignShop but only if you disable all of their sign functions which means you cannot use their sign coloring option. Another thing that you could do, if the Minecraft version you are using is new enough, is you can right click a sign with a piece of dye before you link it with the redstone.

**Comment by RAPHAEL599** [comment]
I got it, thanks
