### ISSUE TITLE
Displaying colors on items when they are not colored, only named!

### ISSUE THREAD

**Issue by TomLewis** [wargamer/SignShop#146]
We have had some scamming happening on the server, where players are pretending to have items that they do not!
Players can not put color onto items, only server items have colors, so these are worth more.

Players are using an anvil to put color codes before item names, they do not show up on the item, but Signshop formats the color codes! Which makes these items look like they are real! So people have been scamming people in trades with shops.

This is the actual item, it should NOT be colored in signshop!

![image(4)](https://user-images.githubusercontent.com/144046/170890192-6abd2bab-086c-41b5-85d6-815a1eee2b90.png)

How signshop is formatting

![image(3)](https://user-images.githubusercontent.com/144046/170890195-f5de68f5-4093-47c8-a754-a714c744cad1.png)

**Comment by weaves7** [comment]
This was caused by an oversight in the implementation of customizable colors in messages that was added a couple years ago. I shared a dev build with you on Discord. Let me know if it works ok and I will PR and add it to the next release.

**Comment by TomLewis** [comment]
It looks likes the fix is working!
