### ISSUE TITLE
Shift+right click via CMI breaks shop signs (even ones you dont have access too)

### ISSUE THREAD

**Issue by TomLewis** [wargamer/SignShop#148]
Shift+right click in CMI allows you to edit signs that you have build permissions for.

Even without permission, if you shift+right click on a signshop sign, it will block you editing it, the sign does not change, but it just breaks it being a shop all together. Not sure why this is happening with signshop.

I will also make a issue with CMI and tag it in here so we can figure out which plugin is at fault! Either way, I have players running around breaking peoples shop signs because they figured this out! Cheeky! Ill remove their perms for now to do it, but its a pain because its such a handy feature to edit signs.

**Comment by weaves7** [comment]
To anyone following along. I believe this is actually a CMI bug. We are waiting to hear from Zrips to see what he has to say.
