### ISSUE TITLE
BugFix

### ISSUE THREAD

**Issue by Cat7373** [wargamer/SignShop#15]
// org/wargamer2010/signshop/listeners/sslisteners/SimpleShopProtector.java

    @EventHandler(priority = EventPriority.LOWEST)
    public void SSBugFix(BlockPlaceEvent event) {
        //By: Cat73, QQ: 1901803382, mail: 1901803382@qq,com, from: china
        Block block = event.getBlock();

        if(block.getType() == Material.SIGN_POST) {
            Location location = block.getLocation();
        //	Player player = event.getPlayer();
        //	player.sendMessage(ChatColor.DARK_GREEN + "you place a signpost(X:" + location.getX() + ", Y:" + location.getY() + ", Z:" + location.getZ() + ").");

            if(Storage.get().getSeller(location) != null) {
            //	player.sendMessage(ChatColor.DARK_GREEN + "fix a bug shop.");
                Storage.get().removeSeller(location);
            }
        }
    }

**Comment by wargamer** [comment]
Thanks for submitting this code. Could you perhaps explain why a fix like this is needed? Because I don't see how a shop can still exist when the sign has been removed (unless serious tampering has been done).

**Comment by Cat7373** [comment]
The following comes from Google Translate.

I am a Chinese people learn English is not very good so do some trouble to explain the feeling they still need to use translation software to segment the video of it - -
As for the repair just anywhere you can listen to this event - -

http://www.cat73.org/ssbug.avi

**Comment by wargamer** [comment]
Hello there, thank you very much for posting the bug report and the fix. I implemented your fix (with a slight adjustment). This is the resulting build: http://69.175.123.170/job/Signshop/65/ and if you click through, you'll find your change implemented with this commit: https://github.com/wargamer/SignShop/commit/0db5ec501c22e5cb0d850ac552c5afdbd34138d1 
Thanks again :)

**Comment by wc7086** [comment]
Front row
