### ISSUE TITLE
Can't Buy Problem (Changing Economy System)

### ISSUE THREAD

**Issue by gadingprakasa** [wargamer/SignShop#150]
So, I was changing from EssentialX to CMI this morning and the sign shop seems to be not working anymore. It's says that I don't have money to pay. It might be related to the eco-system change, and signshop is not aware of this change and recreating new signshop won't solve the problem either. Can you help me? Thank you.

![image](https://user-images.githubusercontent.com/118760184/203118959-19804272-910a-4191-b628-5dbd3fe06b47.png)

**Comment by weaves7** [comment]
Make sure Essentials isn't still in the plugin folder. Make sure CMI economy is enabled fully and using Vault. Make sure the correct Vault version is being used. CMI needs a special one, it is listed on the CMI page.

**Comment by gadingprakasa** [comment]
Alright, I'll do that in a minute. Btw, does punching a chest with item to set up shop still working? Because it's not working on my end.

**Comment by weaves7** [comment]
Punching with the actual item is not a feature. You put the item in the chest in the quantity you want to sell and make a sign. Then hit the chest with redstone and then hit the sign with the redstone. Then fill the shop. For faster support you can join the Discord, btw.

**Comment by gadingprakasa** [comment]
Yeah everything has been sort out. I remember that I read about it somewhere tho. Thank you!
