### ISSUE TITLE
1.20.1 Buy and Sell sign issues

### ISSUE THREAD

**Issue by BanxMagil** [wargamer/SignShop#153]
Hey there! I've recently updated my server to paper 1.20.1 and it seems like we are having issues with the Buy and Sell signs, when interacted with an open hand it brings up the edit sign gui, and regardless of how you interact with it- it always says "The money transaction failed, please contact the System Administrator". The Trade, iBuy, and iSell all work- and I assume that's the case because they arent linked to a person in the same way a Buy or Sell would be. Would this be a possible interference with the economy plugin (we're running the latest version of Gringott's- we use diamonds as currency) or would this be a sign shop issue with 1.20?

**Comment by weaves7** [comment]
IIRC this was caused by either the shop owner not being online and/or not using the Gringotts vault feature. This could also be an issue with trying to use "cents" with item based currency.
