### ISSUE TITLE
Towny + SignShop: Stealing items from chests in an enemy town.

### ISSUE THREAD

**Issue by Monkey0x9** [wargamer/SignShop#17]
If you click a chest in an towny protected area (like an enemy town) with a redstone dust to create a shop, you can create a shop from that chest and then buy everything that is inside that chest. On our server we don't have a chest protector plugin because that is part of our gameplay so the only way to protect a chest is by placing a block on top of it in a protected area (like a town where other people can't break blocks). So when you create an shop from an chest thats not yours you can steal everything from it even if it's protected with a block on top of it.We also don't want to have a max distance of the sign <--> chest. Ideal should be that SignShop can hook into Towny and let the "item_use" permision part of storing a chests container.

**Comment by Devinish** [comment]
After spending some time on this, and looking through the Towny API, we will not be implementing this feature in SignShop.  As far as we can tell, there's no clean way for us to implement something like this, without having a bunch of code in our plugin that we really shouldn't have there.  The best solution would probably be to write an extension plugin for SignShop that would bridge this gap.  Unfortunately, that's not something we are interested in doing at this point.  Thanks for the suggestion.
