### ISSUE TITLE
Change the SignShop Prefix

### ISSUE THREAD

**Issue by i9hdkill** [wargamer/SignShop#22]
Hi,
I couln't find an option to to translate/change the SignShop Prefix.
I know there is an option in ChestShop wasn't able to find it in SignShop.
Any chance you could add such a feature?

**Comment by Devinish** [comment]
Answers to commonly asked questions can be found in our [FAQ](http://dev.bukkit.org/bukkit-plugins/signshop/pages/faq/#w-can-you-make-it-so-we-can-change-the-prefix-in-chat).

**Comment by i9hdkill** [comment]
Maybe you could offer a paid version (advertisement-free) on spigot.
