### ISSUE TITLE
Buying from shops w/ more than one item for sale

### ISSUE THREAD

**Issue by iarepandemonium** [wargamer/SignShop#24]
If you buy from a shop that has multiple items for sale & you either don't have enough money(items) or don't have enough inventory space, it will take your money but give you nothing.

Also, it would be nice if you did have this, if it could FIRST remove the items you are using to pay with from your inventory THEN add the item, because right now it does it the opposite way and if it was reversed they would have enough space.

**Comment by weaves7** [comment]
Since this is an old issue with very little information I am closing it for now. If you still have problems with version 3.4.0+ of SignShop while running Minecraft 1.13.2+ please open a new issue and provide as much information as you can.

**Comment by iarepandemonium** [comment]
No idea, I no longer use this plugin.

**Comment by weaves7** [comment]
I figured that given how long it has been, hence why I closed it. If someone else has the same problem I am sure they will report it.
