### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by CrystalMare** [wargamer/SignShop#25]
There's no way to compile this project. Not even all required jars are provided with the project.

**Comment by wargamer** [comment]
That is indeed a mistake and I've tried to correct it. Ideally the root of the repository would need to move from the source directory to the project directory so the lib and nbproject directories are added to github.
Haven't been able to do that without losing history though.
So for now you can get the dependencies from here: https://dl.dropboxusercontent.com/u/4109728/SignShopLibs.7z

**Comment by CrystalMare** [comment]
You could turn the project into a maven project. You can customize the location of the source and resources.
