### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by GothkittyGirl** [wargamer/SignShop#27]
i noticed that when trying to sell spawn egg it give a egg naes spawn and isnt what i bought and i think it might mess up with potions as well but not tested it

**Comment by GothkittyGirl** [comment]
ok its works fine til a restart of my server then the egg is names spawn right after

**Comment by GothkittyGirl** [comment]
this only happens with spawn eggs atm not tryed potions and its with [iBuy] signs

**Comment by MomaCods** [comment]
ya Same with mine .... any fix for you? I am stumped as to how to sell spawn eggs

**Comment by GothkittyGirl** [comment]
i was running the wrong version of the plugin and have it updated now and seems to work just fine

**Comment by Devinish** [comment]
Glad you found the solution.
