### ISSUE TITLE
Hexdata with Signshop

### ISSUE THREAD

**Issue by Poeschl** [wargamer/SignShop#28]
Hi there,
I have a quick question about using Signshop with Items which just differ by hexData (like the items from Tinkers Construct). Is there a way to do it?

I'm myself a server owner and got this request from one of my players, so I'm currently searching for a solution. After some research I found out that the tools all have the same ID and differ only in the metadata. I remember from prior server plays that chestshop (https://github.com/Acrobot/ChestShop-3) can handle this problem with a suffix with '#' (like DIRT#a) to specify the item. Maybe you could take a look there and build it into SignShop.

**Comment by wargamer** [comment]
We barely have enough time to even support SignShop, let alone add new features to it.
So I'm sorry, we won't be able to help you out. If someone else would like to add this then Pull Requests are more than welcome, assuming the code has been properly tested.

Please read [the top of our dev page](https://dev.bukkit.org/projects/signshop) for more information.
