### ISSUE TITLE
Warning of Overstocked

### ISSUE THREAD

**Issue by MomaCods** [wargamer/SignShop#29]
I noticed someone had posted about this on the comments of the bucket page a link to the latest Dev build was there said it would resolve issue. I have updated to latest dev build and still i recieve the overstocked message

Is there a fix?

**Comment by MomaCods** [comment]
Also it seems it is only with [iTrade] signs

**Comment by MomaCods** [comment]
Anyone?

**Comment by Devinish** [comment]
Typically we take support tickets on the dev.bukkit page.  Please go there and fill out all the required information: http://dev.bukkit.org/bukkit-plugins/signshop/tickets/
