### ISSUE TITLE
Shops which sell Spawn Eggs dont work

### ISSUE THREAD

**Issue by robotnikthingy** [wargamer/SignShop#31]
When I make an [iBuy] signshop which sells any kind of spawn egg, when people buy from it, it just gives a blank spawn egg called "spawn" which does not do anything

basically the same issue as this guy
http://dev.bukkit.org/bukkit-plugins/signshop/tickets/662-spawn-egg-null-issue/

using spigot 1.10
using chestshop 2.11.0Dev

**Comment by Jay9519** [comment]
same problem in spigot 1.11.2
Do the author's ever read these issues?

**Comment by wargamer** [comment]
Yes, we do read the issues here. However, Devinish and I no longer have the time to take care of the issues being reported. Please refer to the message over on our dev.bukkit for more information:
https://dev.bukkit.org/projects/signshop
We still hope someone is willing to take over the project and treat it the same way we did.

**Comment by TheCoolOne123** [comment]
> Yes, we do read the issues here. However, Devinish and I no longer have the time to take care of the issues being reported. Please refer to the message over on our dev.bukkit for more information:
> https://dev.bukkit.org/projects/signshop
> We still hope someone is willing to take over the project and treat it the same way we did.

Please read #56

**Comment by weaves7** [comment]
Fixed in v3+
