### ISSUE TITLE
Plans for SpongeAPI port?

### ISSUE THREAD

**Issue by mcsnetworks** [wargamer/SignShop#32]
Hello,

Was curious if you folks are planning or have any interest in doing a port of this plugin to the SpongeAPI.

Thanks,

**Comment by mcsnetworks** [comment]
Any thoughts on this subject?

**Comment by Devinish** [comment]
We barely have time for developing for Bukkit, let alone another API.  We'd encourage any developers who wanted to do it to do it though.
