### ISSUE TITLE
Game version 1.9.x or 1.10.x support

### ISSUE THREAD

**Issue by tonychee7000** [wargamer/SignShop#33]
Is there any plan ?

**Comment by RoyCurtis** [comment]
FWIW, SignShop seemed to work fine for us on both 1.9.x and 1.10.x

Is there anything in particular about those versions, that is missing or broken in SignShop?

**Comment by adrians416** [comment]
[lTEST!](http://google.com)

**Comment by adrians416** [comment]
(www.github.com)
