### ISSUE TITLE
[request] Storing custom items (Custom heads/items with lore/Brewing support)

### ISSUE THREAD

**Issue by FrozenBeard** [wargamer/SignShop#38]
Hello Signshop team!

PirateCraft is a long time user of SignShop, I have requested these features before, so Im sorry if you recognise this request. Could we please have the option to Store and Sell custom items, this includes:
- Custom Heads, I assume the full data set for storing a custom made head (say from freshcoal) isn't stored properly, as you can set up a shop and sell a head, but as soon as the server restarts all heads revert back to being blank skulls.
- Custom items with Lore; We ran into an issue earlier when we tried to set-up an item sign using a custom item made from essentails that had lore, turns out custom names work, but items with custom lore do not, Im not sure if this bug is just for item signs or in general saving lore.
- Brewing support, this is a third party plugin and may be too complex to save the brew info for each brew into your current database, but its worth a shot asking! https://www.spigotmc.org/resources/brewery.3082/ 

Thank you!

**Comment by wargamer** [comment]
We barely have enough time to even support SignShop, let alone at new features to it.
So I'm sorry, we won't be able to help you out. If someone else would like to add this then Pull Requests are more than welcome, assuming the code has been properly tested.

Please read [the top of our dev page](https://dev.bukkit.org/projects/signshop) for more information.
