### ISSUE TITLE
IXPSell

### ISSUE THREAD

**Issue by SeruhioX** [wargamer/SignShop#43]
Good, I have an error with "ixpsell", if you equip an orb of experience in the left hand (f), jump the error "could not complete operation, contact your system administrator and check the logs", the item is not sold but If that gives you levels of experience.

**Comment by weaves7** [comment]
Since this is an old issue with very little information I am closing it for now. If you still have problems with version 3.4.0+ of SignShop while running Minecraft 1.13.2+ please open a new issue and provide as much information as you can.
