### ISSUE TITLE
Slot's bugged and others

### ISSUE THREAD

**Issue by SeruhioX** [wargamer/SignShop#45]
Bugs have been emerging regarding this feature for a long time.

1 - The probability does not work correctly, if when the slots just do not move the item is much more likely to not touch anything after refilling.

2 - Currently you can insert and remove materials from the slot while it is still working, if a user is playing and the seller is filling, will not get the prize ever, this should be solved by modifying the way to make slots and any changes disable it.

3 - If they fill all the holes of the slot and then remove 52 objects (out of 54), the odds are still 1 in 54, and will never touch the prize or very rarely.

4 - Custom user heads are giving errors.
 4.1 - When the server reboots, they are no longer textured.
 4.2 - If they make a slot with a personalized head and then change it by one
         normal, they get the old head infinitely.

5 - The items with enchantments superior to those of minecraft, become by default to the server restart (especially the swords).

What I ask here is if you can please restructure this mode, since there are many problems, in fact, I do not see how to solve them and I will remove it until it is solved.

**Comment by weaves7** [comment]
Since this is an old issue I am closing it for now. If you still have problems with version 3.4.0+ of SignShop while running Minecraft 1.13.2+ please open a new issue and provide as much information as you can.
