### ISSUE TITLE
iTrade stops working with fireworks since 1.12.1 upgrade.

### ISSUE THREAD

**Issue by Shaskalynae** [wargamer/SignShop#46]
Hello !

We recently upgraded our server from 1.9 to 1.12.1. Everything is fine except that when I create an [itrade] shop that will take specific fireworks from the player's inventory and give him back a paper (Objective to get for the player ranking up), it doesn't work anymore. I put two chests: fireworks trail 1 sec, effect with diamond and one specific color, the paper in the second chest. I punch the first one with the redstone, the second one the same way then the signshop. It works as the [iTrade] becomes blue. But when I want to exchance those fireworks for the piece of paper, it tells me that I don't have the items needed and shops me in the chat windows that I need fireworks, but it's written twice instead of once for the itrade signs placed before the update, if I haven't these in my inventory.

Did I miss something ? I didn't see anything related to this issue.

Any help is welcome !

**Comment by weaves7** [comment]
Since this is an old issue with very little information I am closing it for now. If you still have problems with version 3.4.0+ of SignShop while running Minecraft 1.13.2+ please open a new issue and provide as much information as you can.
