### ISSUE TITLE
Errors - Unable to make signs correctly

### ISSUE THREAD

**Issue by Kirrasio** [wargamer/SignShop#47]
Spigot version 1.12.2
signshop version 2.11.2

When creating signs it shows a ** on the top line and does not allow regular users to create the sign correctly, it allows op users and admins to create signs. We had added the permission node ---> Signshop.Signs.*

https://pastebin.com/EjJh5CpB

**Comment by Devinish** [comment]
This is an error in the Residence plugin.  I'm guessing SignShop works for OP / Admin because they are immune to whatever that Residence check is.

**Comment by Kirrasio** [comment]
Yea, they need to update API of residence plugin. This change was made like a year ago or more. They simply need to change Residence.getResidenceManager() to Residence.getInstance().getResidenceManager() or ResidenceApi.getResidenceManager()

**Comment by Devinish** [comment]
Ah, makes sense.

**Comment by NorthWestTrees** [comment]
will this be getting fixed in a patch done the road?

**Comment by weaves7** [comment]
Fixed in SignShop v3.4.2
