### ISSUE TITLE
My shops are always overstocked.

### ISSUE THREAD

**Issue by CommanderTvis** [wargamer/SignShop#50]
I can't buy anything because always I get message that the shops are overstocked. What's the problem? 

MC version is 1.12.2. 
Spigot and plugin are latest. 
Here's config.yml https://pastebin.com/pw2q1DRt

**Comment by weaves7** [comment]
Since this is an old issue with very little information I am closing it for now. If you still have problems with version 3.4.0+ of SignShop while running Minecraft 1.13.2+ please open a new issue and provide as much information as you can.
