### ISSUE TITLE
Add an open source licence? 

### ISSUE THREAD

**Issue by weaves7** [wargamer/SignShop#51]
Have you considered adding an open source licence? It may help other submit pr's knowing that if you decide to move on to other things the project could be taken over by someone else. Here is some more info https://opensource.guide/legal/

**Comment by wargamer** [comment]
The dev.bukkit page used to state that SignShop is under a MIT license but you're right, the source never contained a clear LICENSE file. I've added it now though: https://github.com/wargamer/SignShop/blob/master/LICENSE
Feel free PR away 👍
