### ISSUE TITLE
Taking over SignShops

### ISSUE THREAD

**Issue by Segysmundo** [wargamer/SignShop#53]
#49 @Devinish There's someone currently interested in taking over the plugin and updating it to 1.13

He might contact you through private message in spigot and bukkit websites if you want to check it out.

**Comment by wargamer** [comment]
Feel free to fork the SignShop project here on Github, it's under MIT license so everyone's free to modify it. As for the spigot and bukkit pages, I can add whoever's willing to continue SignShop to the bukkit page. Devinish owns the spigot page so you'll have to bug him for that. And as this isn't really an issue and more of an announcement, I'll close it.

**Comment by Devinish** [comment]
I checked both Bukkit and Spigot today, I didn't have any messages.  We would be more than happy to hand off the project to the right folks.

**Comment by Segysmundo** [comment]
Sent you a message on spigot with some details.
