### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [wargamer/SignShop#55]
Hello, I am the developer of the plugin Reserve, a modern economy API with modern economy features in mind. As I am now ready to publicly push the API, I'm currently looking for developers to add support for it.

Link: https://github.com/TheNewEconomy/Reserve

Advantages over Vault:
- Multi-currency support
- Async support using Java's completeable futures
- Optional Extended API to allow third party plugins to add new currencies

Current Plugins that support Reserve:
- Towny
- ChestShop3
- MineBay

Current Providers/Planned Providers:
- The New Economy
- Towny Eco
- GemsEconomy

Thanks in advance,
creatorfromhell

**Comment by weaves7** [comment]
Correct me if I am wrong but I don't think Reserve ever caught on.

**Comment by creatorfromhell** [comment]
Actually, reserve has been gaining a lot of traction recently, especially with economy plugin support

**Comment by weaves7** [comment]
My mistake. How easy is it to support both vault and reserve?

**Comment by creatorfromhell** [comment]
Its fairly easy, most implementations utilize a wrapper class, and implement that way(see quickshop or towny as i wrote the implementations for those)

**Comment by weaves7** [comment]
Do you plan on re-adding the permissions API? Currently SignShop uses Vault for economy and permissions. If I were to add Reserve support users would still need Vault for permissions related things.

**Comment by chelminski** [comment]
"This repository has been archived by the owner on Feb 21, 2023"

You no longer intend to develop the project or provide support?

**Comment by creatorfromhell** [comment]
> "This repository has been archived by the owner on Feb 21, 2023"
> 
> You no longer intend to develop the project or provide support?

I may bring it back, but I'm mostly pushing for vault 2 changes to be pulled on the official vault repo since it addresses my complaints with vault.

**Comment by weaves7** [comment]
I am going to close this based on this information. If you ever finish Reserve just comment or make another one.
