### ISSUE TITLE
Server cant open plugin

### ISSUE THREAD

**Issue by kaabel10** [wargamer/SignShop#70]

**Comment by kaabel10** [comment]
[Server thread/ERROR]: Ambiguous plugin name `SignShop' for files `plugins\SignShop-3.4.4.jar' and `plugins\SignShop-3.4.0.jar' in `plugins'
[17:37:40] [Server thread/ERROR]: Could not load 'plugins\SignShop-3.4.4.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault

Umm... What?

**Comment by weaves7** [comment]
You can't have two SignShop jars in your plugins folder and you need to have [vault](https://www.spigotmc.org/resources/vault.34315/) and an economy plugin supported by vault.

**Comment by kaabel10** [comment]
okay I removed the other signshop I accidentally added before and downloaded vault but it doesn't work

**Comment by weaves7** [comment]
I assure you the plugin does work, lol. Did you install an economy plugin? Pastebin your startup log.

**Comment by kaabel10** [comment]
umm here it is https://pastebin.com/3x2VmGiM
I use the essentsials economy

**Comment by weaves7** [comment]
Download the latest version of SignShop(v3.4.4) remove version 3.4.0 and if you have shops made from before then rename the backup to sellers.yml and remove the other one. If you do not have shops from before then you can just delete the SignShop folder. Restart the server, do not reload or use plugman.

**Comment by kaabel10** [comment]
I tried that before and it didn't work. But now it does!!! Thank u man!

**Comment by weaves7** [comment]
You are welcome. It probably didn't work before because you had two SignShop jars in the plugins folder.

**Comment by kaabel10** [comment]
Okay now I got it, but when I use the sell shops it asks me if I wanna sell. How to I get rid of that/say yes?

**Comment by kaabel10** [comment]
Oh wait, it works now.

**Comment by weaves7** [comment]
Unless I am misunderstanding your issue you need to right click instead of left clicking. If right clicking does not help, post a screenshot of the message. You could also join the discord https://discord.gg/czPJg7a

**Comment by kaabel10** [comment]
Got it to work now. Joined the server if i need anything else. Thank u for all the help!
