### ISSUE TITLE
The signshop will not work in a residence

### ISSUE THREAD

**Issue by mrjesen** [wargamer/SignShop#73]
The Signshop will not work in a residence(created by the plugin named Residence).
**when the op right click the sign it will work 
but normal players right click the sign,it will not work.**

in the public place(not a residence),all the players can click.
_i am sure that the plugin is loaded successfully._

(my english is not good, thanks)

**Comment by mrjesen** [comment]
left click the sign,it will give correct tip

**Comment by weaves7** [comment]
What server version, signshop version, residence version, vault version and the name and version of your economy plugin? Please also put your latest.log into a pastebin, save and post the link here.

**Comment by mrjesen** [comment]
Server version: Paper version git-Paper-105 (MC: 1.15.2)
signshop version: 3.4.4
residence version : 4.9.0.5
vault version: 1.7.2-b107

latest.log: echo no error log  ....

**Comment by weaves7** [comment]
You should still have a latest.log even if there is no error. It is in ./logs/latest.log

**Comment by mrjesen** [comment]
[https://paste.ubuntu.com/p/rhmXYfHRx4/](https://paste.ubuntu.com/p/rhmXYfHRx4/)
line 1815-1845

**Comment by weaves7** [comment]
That doesn't show me much other than your server crashed at some point but I don't think it is related. Do the players get a message in chat when it stops them from clicking the sign?
What kind of signs are you using? Can the players make shops in their own residence? And can players use their own shops?

**Comment by mrjesen** [comment]
[Repair] and [Buy] is what i'm using.
whene the plain user try to link the chest to the sign it will tip: You have no permission to link the type of chest.

**Comment by weaves7** [comment]
Give the plain user the `signshop.signs.*` permission so they can create all non-op signs. Plain users should not be able to create [Repair] signs it is only for ops to create. They should be able to use the sign though. When the plain user right clicks the sign does it give them a message?

**Comment by mrjesen** [comment]
When the plain user right clicks the sign does it give them a message?
they doesnt get any message in their clint.

**Comment by mrjesen** [comment]
i have gived them the permission(signshop.signs.*)

**Comment by weaves7** [comment]
They may be too close to the vanilla spawn protection zone. Try setting it to 0 in server.properties.

**Comment by mrjesen** [comment]
https://ftp.bmp.ovh/imgs/2020/05/493027a199f1678f.png

**Comment by mrjesen** [comment]
> They may be too close to the vanilla spawn protection zone. Try setting it to 0 in server.properties.

but in other residence , it still doesn't work

**Comment by weaves7** [comment]
> https://ftp.bmp.ovh/imgs/2020/05/493027a199f1678f.png
what does the second line of that say in english?

> but in other residence , it still doesn't work
So not that then. Do `/lp verbose on` and see what permissions are checked when they try to click the sign without op.

**Comment by mrjesen** [comment]
> https://ftp.bmp.ovh/imgs/2020/05/493027a199f1678f.png

line2: the group default already have the permisson.

**Comment by mrjesen** [comment]
https://s1.ax1x.com/2020/05/11/YGnbTI.png

**Comment by mrjesen** [comment]
the player(optest) is not op

**Comment by mrjesen** [comment]
in the place(not residence) it will link successfully.
in the residence it will link failed.

**Comment by mrjesen** [comment]
public area: https://i.loli.net/2020/05/11/4mV3WJLCr7Xb12U.png
residence area:https://i.loli.net/2020/05/11/MRy9BLkmOgqDtT8.png

**Comment by weaves7** [comment]
What does the chat say in english on the second picture?

**Comment by mrjesen** [comment]
> What does the chat say in english on the second picture?

line1: you need to link at least 1 chest to this shop
line2: you dont have permisson to link this.

**Comment by weaves7** [comment]
Does that player own that residence?

**Comment by mrjesen** [comment]
yes, the player is the owner of the residence

**Comment by weaves7** [comment]
Does optest have other groups besides default?

**Comment by mrjesen** [comment]
> Does optest have other groups besides default?

no,and even the server has only one group:default

**Comment by weaves7** [comment]
open up an editor for the default group and send me the link

**Comment by mrjesen** [comment]
emm, i cannt find the file

**Comment by weaves7** [comment]
in game do `/lp editor` then paste the link it gives you in chat here

**Comment by mrjesen** [comment]
https://editor.luckperms.net/fNqD5bJHFh

**Comment by weaves7** [comment]
do `/lp applyedits idwbIqh8hf`

**Comment by mrjesen** [comment]
sorry,it still doesnot work.......................................

**Comment by weaves7** [comment]
Can I join your server to test?

**Comment by mrjesen** [comment]
yes, the ip:port is : mc1.ddwhm.com:25588

**Comment by mrjesen** [comment]
the server is in china,maybe your delay will be very big

**Comment by weaves7** [comment]
what is the register message in english?

**Comment by mrjesen** [comment]
reg:   /register password password
login: /l password

**Comment by mrjesen** [comment]
goodbye~

**Comment by mrjesen** [comment]
we can chat on telegram, my username is jesenv5

**Comment by weaves7** [comment]
I don't have telegram, github is ok; or your server.
Notes from visiting the server:
- Server is in offline mode
- Seems to be a problem with the container flag with residence, when flag is true shops can be made but others can steal; when flag is false others can't steal but you can't make a shop. 

May try:
`/res pset [PlayerName] container true`

**Comment by mrjesen** [comment]
> I don't have telegram, github is ok; or your server.
> Notes from visiting the server:
> 
> * Server is in offline mode
> * Seems to be a problem with the container flag with residence, when flag is true shops can be made but others can steal; when flag is false others can't steal but you can't make a shop.
> 
> May try:
> `/res pset [PlayerName] container true`

wow, I thought you went to bed .
I will try. Sorry for my disturbing.
goodnight~

**Comment by weaves7** [comment]
> > I don't have telegram, github is ok; or your server.
> > Notes from visiting the server:
> > 
> > * Server is in offline mode
> > * Seems to be a problem with the container flag with residence, when flag is true shops can be made but others can steal; when flag is false others can't steal but you can't make a shop.
> > 
> > May try:
> > `/res pset [PlayerName] container true`
> 
> wow, I thought you went to bed .
> I will try. Sorry for my disturbing.
> goodnight~

Did you ever try that?

**Comment by mrjesen** [comment]
I tried that and it works.

**Comment by weaves7** [comment]
> I tried that and it works.

Although that is an ok temporary fix I have released a dev version that allows the owner of a residence to always bypass the check without the flag being set for them. You can find it here: https://github.com/weaves7/SignShop/releases/tag/v3.4.10 If you could give it a try and let me know if this is a better solution it would be appreciated. The flag should still be able to be used for the owner of a residence to allow their friends to create shops as well.

**Comment by mrjesen** [comment]
I have tried that and it works.
thanks for your hard working~
