### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by urhumblnarrator** [wargamer/SignShop#76]
The Plugin seems to work fine as in, I can make the signs and setup the shop, but even if I have a balance that CAN pay whatever i put on the sign, it says i dont, so i dont know if it's a compatibility problem.

I'm using Ultimate_Economy 1.2.5 as my Vault economy plugin
Minecraft Server is 1.14.2
3.4.4 signshop

**Comment by weaves7** [comment]
Adding Ultimate_Economy to the list of SignShop's soft dependencies fixes this in SignShop v3.4.7 and later.
