### ISSUE TITLE
Users can use dye on signs

### ISSUE THREAD

**Issue by SeruhioX** [wargamer/SignShop#77]
I leave the issue here so you watch it when you can.

If I make a "[buy]" sign in which the item inside the chest is a dye, users can use this object to change the color of the letters of the sign and disable it.
Bypassing the WorldGuard restrictions, this doesn't happen if the item to buy is not a dye.

Signshop 3.4.4
PaperSpigot 1.15.2

error: https://gyazo.com/89b2a585d9fbe5ebb0f868ab0a174ff4   
ITEM: https://i.gyazo.com/ae25ad0d3a4858769e84f206412e709d.png  
plugins: https://i.gyazo.com/4341808271111efdb6ecb04d0d35b6b7.png

**Comment by weaves7** [comment]
Do you still have this problem with the latest version? I have not been able to reproduce the issue.

**Comment by weaves7** [comment]
![unknown](https://user-images.githubusercontent.com/24948806/185763278-364e9d45-1cee-4e37-aa25-62ce563dd4cd.jpg)


Thangss — Today at 2:13 PM
oh

Eman — Today at 2:13 PM
Checked the trustlist in that place, she doesn't have any trust
[2:13 PM]


Thangss — Today at 2:14 PM
So she bought the glow ink, and it used one on the sign, interesting. I tried with reg dye at Ikea and that didnt hppen. Might just be glow ink

Eman — Today at 2:14 PM
Yeah could be

Weaves — Today at 2:16 PM
Sounds similar to this issue that was reported but I could never duplicate it and the reporter disappeared. https://github.com/wargamer/SignShop/issues/77
[2:17 PM]
Could you provide as much information about that issue as you can?

Thangss — Today at 2:17 PM
I dont think it's being disabled tho.

Weaves — Today at 2:17 PM
Still probably shouldn't be able to dye someone elses shop

Thangss — Today at 2:19 PM
![2022-08-20_15 18 57](https://user-images.githubusercontent.com/24948806/185763314-6d4771f6-4be6-4a26-9fcc-8185518658cf.jpg)

[2:19 PM]
pretty  much sums it up. It dyed the sign, charged me for it, and I didnt get the glow ink sac
[2:20 PM]
I was able to buy a second one no problem

Eman — Today at 2:20 PM
Yeah seems like if u buy it it uses it at the same time, and doesn't care about the claim when u do both at the same time

Thangss — Today at 2:20 PM
Yeah I have trust in that claim

Eman — Today at 2:22 PM
Welp, I just tried it without trust and it still did it

Weaves — Today at 2:26 PM
well now that I know how to reproduce the issue i may be able to fix it. And it would be a good time to add the dye on purpose feature

Message #support
