### ISSUE TITLE
Improper Shutdown of Async Tasks

### ISSUE THREAD

**Issue by SentientScythe** [wargamer/SignShop#78]
Hello,
I'm getting this message in my logs:
[Server thread/ERROR]: Nag author: 'Wargamer2010' of 'SignShop' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

    Server: Paper 1.15.2 #300
    SignShop: 3.4.4
    Vault: 1.7.2
    Economy plugin: Gringotts 2.11.2

[https://pastebin.com/Q02LZS59](https://pastebin.com/Q02LZS59)

**Comment by weaves7** [comment]
> Hello,
> I'm getting this message in my logs:
> [Server thread/ERROR]: Nag author: 'Wargamer2010' of 'SignShop' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
> 
> ```
> Server: Paper 1.15.2 #300
> SignShop: 3.4.4
> Vault: 1.7.2
> Economy plugin: Gringotts 2.11.2
> ```
> 
> https://pastebin.com/Q02LZS59

Does this happen every time? Are you doing /stop /restart or /reload? Or are you using Plugman when it happens?
