### ISSUE TITLE
Minecraft 1.8 compatibility

### ISSUE THREAD

**Issue by Wilmerbox** [wargamer/SignShop#79]
I have seen that they updated the plugin. I really like this plugin, I would like to know if it is possible to create a version for spigot 1.8 that allows you to change the prefix, if necessary I can contribute some money. Thank you.

**Comment by weaves7** [comment]
After some consideration I do not currently want to add features to legacy versions. Especially not ones that the original authors were against. I am glad you like the plugin and you could always go back and fork the project and run a custom version.
