### ISSUE TITLE
"Nag author" error

### ISSUE THREAD

**Issue by Srborjaa** [wargamer/SignShop#80]
![imagen](https://user-images.githubusercontent.com/29895095/84534247-dc346480-ace9-11ea-9859-56871a8f7708.png)

Hi, when I stop the server using /stop, /restart and /reload, this error appears. I've seen that another plugin "ServerSigns" is showing that error but I don't know why.

Weaves asked me for the startup log and timings.yml:

https://pastebin.com/TqZHDxtx (startup log)

https://gyazo.com/2f74835fb0db2094150777770d43ded6

Thanks.

**Comment by weaves7** [comment]
duplicates #78
