### ISSUE TITLE
[Suggestion] Write log file when players buy

### ISSUE THREAD

**Issue by mrjesen** [wargamer/SignShop#81]
Write log file when players right click the [iBuy] or [iSell] sign.

Now there are many players sells their items but i cannot know how much, what or when they sell.

So,please add this function~

**Comment by weaves7** [comment]
> Write log file when players right click the [iBuy] or [iSell] sign.
> 
> Now there are many players sells their items but i cannot know how much, what or when they sell.
> 
> So,please add this function~

I have good news, this is already a feature! 
In your config change `TransactionLog: false` to `TransactionLog: true`.
