### ISSUE TITLE
I have a problem with BentoBox Hook

### ISSUE THREAD

**Issue by Superfudge247** [wargamer/SignShop#84]
I am trying to use the 1.15 version of signshops I love this plugin however I am having an issue when I have bento box in my plugins folder I can only use signshops on my skyblock island however I want to have players be able to use other worlds to make their own player markets but they are restricted to there island and can't use the plugin outside of that

**Comment by weaves7** [comment]
Try this dev build. https://github.com/weaves7/SignShop/releases/tag/v3.4.11

There is also a PR that may be even better but I still need to look at it.
