### ISSUE TITLE
BentoBox and Compile issue

### ISSUE THREAD

**Issue by andrewfer000** [wargamer/SignShop#88]
Hello! I use BentoBox and I cannot create shops in my spawn world but I do not have an issue on the island world. I see you fixed it in your source code recently and I tried to compile but it failed. How can I fix the issue with the current version or compile the source? (I use` mvn clean package install `on Ubuntu 20.04 to compile) Also I use Paper 1.16.1

**Comment by andrewfer000** [comment]
Here is the compile issue.
[ERROR] Failed to execute goal on project SignShop: Could not resolve dependencies for project org.makershaven:SignShop:jar:3.4.4: The following artifacts could not be resolved: com.sk89q.worldguard.bukkit:worldguard:jar:7.0.0, com.sk89q.worldedit.bukkit:worldedit:jar:7.1.0, com.palmergames.bukkit:towny:jar:0.95.1.0-1.13.2, com.bekvon.bukkit:residence:jar:4.8.8.2, com.earth2me:essentials:jar:2.17.1.0, org.dynmap.bukkit:dynmap:jar:3.0-beta-10-257, com.Zrips:CMI:jar:8.5.1.2: Failure to find com.sk89q.worldguard.bukkit:worldguard:jar:7.0.0 in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]

**Comment by andrewfer000** [comment]
Okay I fixed the world issue by using the dev build. But I would still like to be able to compile the source code to make changes and/or contribute.

**Comment by weaves7** [comment]
Install those jars in your local maven repository, some or all of them are not publicly available; either they are closed source or the pom.xml needs updated. Just as a heads up my fork is quite a ways ahead of this one so you may want to go through it before you make changes that I already have. Once I test them fully I will PR them.

**Comment by andrewfer000** [comment]
Oh okay thanks for the infos. I am still kinda new at plugin development and I do not know much about Maven yet. I'll try to figure it out.
