### ISSUE TITLE
[Suggestions] Brewery Plugin Support

### ISSUE THREAD

**Issue by YouthInRevolt** [wargamer/SignShop#89]
Selling items from the brewery plugin only allows the linked item to be sold and none of the other items of the same drink. It'd be cool to have this plugin supported with sign shop.

**Plugin:** https://www.spigotmc.org/resources/brewery.3082/

**Comment by weaves7** [comment]
Can you explain in more detail what you want, with examples?

**Comment by weaves7** [comment]
Not sure what the reporter wants. You can buy and sell brews.
