### ISSUE TITLE
Trading does not work with named items (and some other trade issues)

### ISSUE THREAD

**Issue by andrewfer000** [wargamer/SignShop#90]
Not sure if this was noticed before but when I was setting up a trade, I could not have the user trade in a special named item. Based on my testing this only is broken for trading. (I am using your latest dev version w/ Bentobox

**Comment by andrewfer000** [comment]
Also, Once a trade goes out of stock it does not detect re-stocks needs to be re-made entirely.

**Comment by weaves7** [comment]
Duplicates #83
