### ISSUE TITLE
SignShop doesn't allow linking chest no matter what permissions are used or if the player has OP

### ISSUE THREAD

**Issue by Budderman18** [wargamer/SignShop#93]
Whenever I try and link a chest, it won't link. No matter what settings i change in either SignShop or Group manager, this doesn't fix. However, chests DO link in one of my worlds, yet i see no reason why as there isn't anything special in any world file.

Spigot 1.16.1

SignShop 3.4.4

Vault 1.7.3-b131

EssentialsX 2.18.0.0

My entire console from startup to attempting to link a chest to shutdown: https://pastebin.com/2uaNDCcp

i don't understand this at this point. If i needs to provide more i will do so.

**Comment by weaves7** [comment]
Try this dev build: https://github.com/weaves7/SignShop/releases/tag/v3.4.11

**Comment by Budderman18** [comment]
The dev build fixed this. Thank you!
