### ISSUE TITLE
[1.16] Plugin is not properly shutting down

### ISSUE THREAD

**Issue by rhystedstone** [wargamer/SignShop#94]
```[22:47:48 ERROR]: Nag author: 'Wargamer2010' of 'SignShop' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.```

Despite being a very minor issue, it does say to nag 😄
Although, I am attempting to run SignShop on 1.16, despite that, no errors arise bar that.

Edit: Yes, I know it doesn't _officially_ support 1.16

**Comment by weaves7** [comment]
> Despite being a very minor issue, it does say to nag 😄

Lol, sometimes nagging does help. Here is a pre-release with this already fixed and some other fixes, https://github.com/weaves7/SignShop/releases/tag/v3.4.13

**Comment by rhystedstone** [comment]
Oh, thanks, I wasn't running this on a production server, so I'll add it right now, again, thanks!
