### ISSUE TITLE
Kits Problem

### ISSUE THREAD

**Issue by llaya** [wargamer/SignShop#99]
When you make 2 different [Kit] Signs, and a player uses 1, the other one gives an error; "you can only use this shop once" Even tho it's a different sign.
Is there a way to have Kit shops be seperated and work on there own timer instead of having it global for all signs?

Elaboration;
If i make a [Kit] sign and link it to a chest with a diamond sword, and i make a [Kit] sign linked to a chest with a shield, and ask a player to activate them both, only the first activated [Kit] sign will give the items, and the other kit sign will not work anymore, meaning players would have to effectively choose which kit they would want more.

My problem is that i wanted to use [Kit] signs for a treasure hunt, where i would have a few different [Kit] signs hidden away, so players who find them can use them once to get some nice goodies, as a reward for exploration.
This is the same problem with Custom signs with a delay based on the Kit system.

**Comment by weaves7** [comment]
Although I have not tried it you should be able to make multiple kit signs in the config. The config already contains [Kit] so you could make [KitTwo] for example or you could make a totally different sign such as [TreasureOne] and just copy over the operations from the Kit and all of the messages and edit them to your liking. The key is you will need a different sign name for each reward when used with the ``oneTime`` SignShop operation.

**Comment by weaves7** [comment]
Assuming this has been resolved. Re-open with more information if it is not.
